on:
  workflow_dispatch:
  push:
    branches: [main]

name: Quarto Render and Publish One File

jobs:
  render-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render final_project.ipynb
        run: quarto render final_project.ipynb

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: _site  # Quarto outputs here by default
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
