on:
  workflow_dispatch:
  push:
    branches: [main]

name: Quarto Render and Publish One File

jobs:
  render-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Jupyter
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render final_project.ipynb
        run: quarto render final_project.ipynb

      - name: Set git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Publish final_project.ipynb to GitHub Pages
        run: quarto publish gh-pages final_project.ipynb --no-prompt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


